make test pass; intentionally fail deploy job

diff --git a/.github/workflows/execution-flow.yml b/.github/workflows/execution-flow.yml
--- a/.github/workflows/execution-flow.yml
+++ b/.github/workflows/execution-flow.yml
@@ -33,7 +33,6 @@ jobs:
           key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
       - name: Install dependencies
         run: npm ci
-
       - name: Test code
         id: run-tests
         run: npm run test
@@ -43,6 +42,7 @@ jobs:
         with:
           name: test-report
           path: test.json
+  
   build:
     needs: test
     runs-on: ubuntu-latest
@@ -65,6 +65,7 @@ jobs:
         with:
           name: dist-files
           path: dist
+
   deploy:
     needs: build
     runs-on: ubuntu-latest
@@ -77,7 +78,9 @@ jobs:
       - name: Output contents
         run: ls
       - name: Deploy
-        run: echo "Deploying..."
+        run: |
+          echo "Deploying..."
+          exit 1
   
   report:
     runs-on: ubuntu-latest
@@ -87,7 +90,7 @@ jobs:
       - name: echo  -e "report failure report"
         run: echo -e "report failure report"
 
-  # Still runs even though notifiy only needs the deploy job, which is skipped due to the test job failure
+  # The notify job still runs even though it only needs the deploy job, which is skipped due to the test job failure
   # Why? A status of 'skipped'  counts as a failure-related state, and so here failure() returns true
   notify:
     runs-on: ubuntu-latest
@@ -97,4 +100,4 @@ jobs:
       - name: notify
         run: |
           echo  -e "notify failure report"
-          echo  -e "\n\tValidating notify job runs due to deploy job being skipped, not because deploy.result == 'failure': ${{ needs.deploy.result }}"
+          echo  -e "\nValidating notify job runs due to deploy job being skipped, not because deploy.result == 'failure': ${{ needs.deploy.result }}"
